/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ADDRESS_CUSTOMER extends javax.swing.JFrame {
String username;
Integer identity;
    /**
     * Creates new form ADDRESS_CUSTOMER
     */
    public ADDRESS_CUSTOMER() {
        initComponents();
    }
    public ADDRESS_CUSTOMER(String user) {
        username = user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLogo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("CITY");
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(70, 300, 70, 14);
        jLayeredPane2.add(jTextField1);
        jTextField1.setBounds(70, 160, 340, 30);

        jLogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_logo(Low).png"))); // NOI18N
        jLayeredPane2.add(jLogo1);
        jLogo1.setBounds(60, 40, 102, 52);

        jLabel2.setText("STREET ADDRESS");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(70, 140, 140, 14);

        jLabel3.setText("STATE");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(330, 300, 70, 14);

        jLabel4.setText("COUNTRY");
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(70, 340, 70, 14);

        jLabel5.setText("PINCODE");
        jLayeredPane2.add(jLabel5);
        jLabel5.setBounds(330, 340, 50, 14);
        jLayeredPane2.add(jTextField2);
        jTextField2.setBounds(70, 200, 340, 30);
        jLayeredPane2.add(jTextField3);
        jTextField3.setBounds(70, 240, 340, 30);
        jLayeredPane2.add(jTextField6);
        jTextField6.setBounds(390, 330, 100, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 100, 153));
        jButton2.setText("Add Address");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton2);
        jButton2.setBounds(190, 440, 150, 40);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jTextField4);
        jTextField4.setBounds(140, 290, 100, 30);
        jLayeredPane2.add(jTextField7);
        jTextField7.setBounds(390, 290, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangladesh", "Bhutan", "China", "India", "Mayanmar", "Nepal", "Pakistan", "Sri Lanka", "United States ", "United Kingdom", " " }));
        jLayeredPane2.add(jComboBox2);
        jComboBox2.setBounds(140, 340, 100, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 100, 153));
        jLabel7.setText(" SIGN UP HERE");
        jLabel7.setOpaque(true);
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(180, 90, 190, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_Signup.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(10, -10, 540, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String line1 =jTextField1.getText();
        String line2 =jTextField2.getText();
        String line3 =jTextField3.getText();
        String city =jTextField4.getText();
        String state =jTextField7.getText();
        String country = (String)jComboBox2.getSelectedItem();
        String pincode =jTextField6.getText();

        if (line1.isEmpty())
        JOptionPane.showMessageDialog(this,"Street address not Entered");
        else if (line2.isEmpty())
        JOptionPane.showMessageDialog(this,"Street address not entered");
        else if (city.isEmpty())
        JOptionPane.showMessageDialog(this,"city not entered");
        else if (state.isEmpty())
        JOptionPane.showMessageDialog(this,"state not entered");
        else if (pincode.isEmpty())
        JOptionPane.showMessageDialog(this,"pincode not entered");
        else if (country.isEmpty())
        JOptionPane.showMessageDialog(this,"country not entered");

        else

        try
        {   Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "Insert INTO Addresses   ( `line_1`, `line_2`, `line_3`,`city`, `state`, `country`, `pin_code`, `customer_id`) values('"+line1+"','"+line2+"','"+line3+"','"+city+"','"+state+"','"+country+"','"+pincode+"','"+identity+"');" ;
            stmt.executeUpdate(query);
            con.close();
            stmt.close();
            this.dispose();
            new DASHBOARD_CUSTOMER(identity).setVisible(true);
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {   Class.forName("java.sql.DriverManager");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt1 = (Statement) con1.createStatement();
            String a = "Select customer_id from  Customers where customer_username = '"+ username+"';";
            ResultSet rs=stmt1.executeQuery(a);
            int id = 1;
            while (rs.next())
            {
                 id = rs.getInt("customer_id");
            }
            identity = id;
            con1.close();
            stmt1.close();
            
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDRESS_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDRESS_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDRESS_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDRESS_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDRESS_CUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel jLogo1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
