/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class BILLING extends javax.swing.JFrame {
Integer identity;
    /**
     * Creates new form BILLING
     */
    public BILLING() {
        initComponents();
    }
    
    public BILLING(Integer id) {
        identity = id;        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLogo1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 100, 153));
        jButton1.setText("Search Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(280, 150, 150, 25);

        jComboBox1.setModel(new  DefaultComboBoxModel());
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jLayeredPane1.add(jComboBox1);
        jComboBox1.setBounds(130, 150, 90, 20);

        jLabel6.setText("PACKAGE WEIGHT");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(70, 220, 100, 14);

        jLabel7.setText("DELIVERY TYPE");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(70, 280, 90, 14);

        jLabel8.setText("PACKAGE TYPE");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(280, 220, 90, 14);

        jTextField1.setEditable(false);
        jLayeredPane1.add(jTextField1);
        jTextField1.setBounds(180, 220, 80, 20);

        jTextField2.setEditable(false);
        jLayeredPane1.add(jTextField2);
        jTextField2.setBounds(370, 220, 80, 20);

        jTextField3.setEditable(false);
        jLayeredPane1.add(jTextField3);
        jTextField3.setBounds(180, 280, 80, 20);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 100, 153));
        jButton2.setText("GENERATE BILL");
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(110, 460, 160, 25);

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 100, 153));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3);
        jButton3.setBounds(300, 460, 150, 25);

        jTextField4.setEditable(false);
        jLayeredPane1.add(jTextField4);
        jTextField4.setBounds(270, 380, 160, 20);

        jLabel1.setText("TOTAL AMOUNT");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(120, 380, 100, 14);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 100, 153));
        jButton4.setText("CALCULATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4);
        jButton4.setBounds(200, 340, 160, 25);

        jLogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_logo(Low).png"))); // NOI18N
        jLayeredPane1.add(jLogo1);
        jLogo1.setBounds(30, 30, 102, 52);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 100, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BILLING");
        jLabel10.setOpaque(true);
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(130, 80, 260, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/BAckground.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(0, 0, 540, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultComboBoxModel m1 =(DefaultComboBoxModel) jComboBox1.getModel();
        
        try{
            m1.removeAllElements();
            Class.forName("java.sql.DriverManager");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt1 = (Statement) con1.createStatement();
            String q1 = "SELECT  package_id FROM Packages where customer_id = "+ identity+";";
            ResultSet rs = stmt1.executeQuery(q1);

            while( rs.next())

            {
                String a = rs.getString("package_id");
                m1.addElement(a);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String id = (String) jComboBox1.getSelectedItem();
        try
        {   Class.forName("java.sql.DriverManager");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt1 = (Statement) con1.createStatement();
            String a = "Select `package_weight`,`package_type`, `package_delivery_type` from "
                    + " Packages where   package_id = "+ id +";";
            ResultSet rs=stmt1.executeQuery(a);
            
            while (rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                
            }
           
            con1.close();
            stmt1.close();
            
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.dispose();
    new DASHBOARD_CUSTOMER(identity).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int weight = Integer.parseInt(jTextField1.getText());
        String type = jTextField2.getText();
        String delivery = jTextField3.getText();
        int type_amount;
        int delivery_amount;
        int Total;
    switch (type) {
        case "Regular":
            type_amount = 5;
            break;
        case "Fragile":
            type_amount = 10;
            break;
        case "Waterproof":
            type_amount = 10;
            break;
        case "Gold":
            type_amount = 15;
            break;
        case "Premium":
            type_amount = 20;
            break;
        default:
            type_amount = 5;
            break;}
    
        switch (delivery) {
        case "Regular":
            delivery_amount = 5;
            break;
        case "Superfast":
            delivery_amount = 10;
            break;
        case "Premium":
            delivery_amount = 15;
            break;
        default:
            delivery_amount = 5;
            break;
        }
        Total = (type_amount + delivery_amount) * 20 + weight * 20;
        jTextField4.setText("" + Total + " Rupees");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLogo1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
