/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ORDERPACKAGE extends javax.swing.JFrame {
Integer identity;
    /**
     * Creates new form ORDERPACKAGE
     */
    public ORDERPACKAGE() {
        initComponents();
    }
    
    public ORDERPACKAGE(Integer id) {
        identity = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLogo1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CITY");
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(60, 400, 70, 14);
        jLayeredPane2.add(jTextField1);
        jTextField1.setBounds(60, 260, 300, 30);

        jLabel2.setText("STREET ADDRESS");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(60, 240, 140, 14);

        jLabel3.setText("STATE");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(320, 400, 70, 14);

        jLabel4.setText("COUNTRY");
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(60, 440, 70, 14);

        jLabel5.setText("PINCODE");
        jLayeredPane2.add(jLabel5);
        jLabel5.setBounds(320, 440, 50, 14);
        jLayeredPane2.add(jTextField2);
        jTextField2.setBounds(60, 300, 300, 30);
        jLayeredPane2.add(jTextField3);
        jTextField3.setBounds(60, 340, 300, 30);
        jLayeredPane2.add(jTextField6);
        jTextField6.setBounds(380, 430, 100, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 100, 153));
        jButton2.setText("OREDER PACKAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton2);
        jButton2.setBounds(90, 480, 170, 25);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jTextField4);
        jTextField4.setBounds(130, 390, 100, 30);
        jLayeredPane2.add(jTextField7);
        jTextField7.setBounds(380, 390, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangladesh", "Bhutan", "China", "India", "Mayanmar", "Nepal", "Pakistan", "Sri Lanka", "United States ", "United Kingdom", " " }));
        jLayeredPane2.add(jComboBox2);
        jComboBox2.setBounds(130, 440, 100, 20);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 100, 153));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton1);
        jButton1.setBounds(300, 480, 160, 25);

        jLabel6.setText("PACKAGE WEIGHT");
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(60, 140, 100, 14);

        jLabel7.setText("DELIVERY TYPE");
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(60, 200, 90, 14);

        jLabel8.setText("PACKAGE TYPE");
        jLayeredPane2.add(jLabel8);
        jLabel8.setBounds(270, 130, 90, 14);

        jLabel9.setText("DELIVERY ADDRESS");
        jLayeredPane2.add(jLabel9);
        jLabel9.setBounds(60, 220, 120, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Fragile", "Waterproof", "Gold", "Premium" }));
        jLayeredPane2.add(jComboBox1);
        jComboBox1.setBounds(370, 130, 100, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Superfast", "Premium" }));
        jLayeredPane2.add(jComboBox3);
        jComboBox3.setBounds(170, 200, 80, 20);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(5, 1, 15, 1));
        jLayeredPane2.add(jSpinner1);
        jSpinner1.setBounds(170, 140, 39, 20);

        jLogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_logo(Low).png"))); // NOI18N
        jLayeredPane2.add(jLogo1);
        jLogo1.setBounds(30, 30, 102, 52);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 100, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ORDER PACKAGE");
        jLabel11.setOpaque(true);
        jLayeredPane2.add(jLabel11);
        jLabel11.setBounds(160, 80, 240, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/BAckground.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel10);
        jLabel10.setBounds(0, 0, 540, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String type = (String)jComboBox1.getSelectedItem();
        String delivery = (String)jComboBox3.getSelectedItem();
        String weight; 
        weight = String.valueOf( jSpinner1.getValue());
        String line1 =jTextField1.getText();
        String line2 =jTextField2.getText();
        String line3 =jTextField3.getText();
        String city =jTextField4.getText();
        String state =jTextField7.getText();
        String country = (String)jComboBox2.getSelectedItem();
        String pincode =jTextField6.getText();

        if (line1.isEmpty())
        JOptionPane.showMessageDialog(this,"Street address not Entered");
        else if (line2.isEmpty())
        JOptionPane.showMessageDialog(this,"Street address not entered");
        else if (city.isEmpty())
        JOptionPane.showMessageDialog(this,"city not entered");
        else if (state.isEmpty())
        JOptionPane.showMessageDialog(this,"state not entered");
        else if (pincode.isEmpty())
        JOptionPane.showMessageDialog(this,"pincode not entered");
        else if (country.isEmpty())
        JOptionPane.showMessageDialog(this,"country not entered");

        else

        try
        {   Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "Insert INTO Packages   (  `customer_id`,  `package_weight`,   `package_type`, `package_delivery_type`, `line_1`, `line_2`, `line_3`,`city`, `state`, `country`, `pin_code`) values('"+identity+"','"+weight+"','"+type+"','"+delivery+"','"+line1+"','"+line2+"','"+line3+"','"+city+"','"+state+"','"+country+"','"+pincode+"');" ;
            stmt.executeUpdate(query);
            con.close();
            stmt.close();
            JOptionPane.showMessageDialog(this,"Your Package will be delivered");
            defalt();
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new DASHBOARD_CUSTOMER(identity).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORDERPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORDERPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORDERPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORDERPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORDERPACKAGE().setVisible(true);
            }
        });
    }

    /**
     *
     */
    public void defalt()
    {
     jTextField1.setText("");
     jTextField2.setText("");
     jTextField3.setText("");
     jTextField4.setText("");
     jTextField7.setText("");
     jTextField6.setText("");
     jComboBox1.setSelectedIndex(0);
     jComboBox2.setSelectedIndex(0);
     jComboBox3.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel jLogo1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}

