/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class SIGNUP_CUSTOMER extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP_CUSTOMER
     */
    public SIGNUP_CUSTOMER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLogo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_logo(Low).png"))); // NOI18N
        jLayeredPane2.add(jLogo1);
        jLogo1.setBounds(60, 40, 102, 52);

        jLabel1.setText("USERNAME");
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(60, 230, 70, 14);
        jLayeredPane2.add(jTextField1);
        jTextField1.setBounds(130, 130, 100, 30);

        jLabel2.setText("FIRST NAME");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(60, 130, 70, 14);

        jLabel3.setText("LAST NAME");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(60, 180, 70, 14);

        jLabel4.setText("PHONE NO");
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(280, 130, 70, 14);

        jLabel5.setText("EMAIL");
        jLayeredPane2.add(jLabel5);
        jLabel5.setBounds(280, 180, 30, 14);

        jLabel6.setText("PASSWORD");
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(60, 290, 80, 14);
        jLayeredPane2.add(jTextField2);
        jTextField2.setBounds(130, 180, 100, 30);
        jLayeredPane2.add(jTextField3);
        jTextField3.setBounds(130, 230, 100, 30);
        jLayeredPane2.add(jTextField5);
        jTextField5.setBounds(350, 130, 100, 30);
        jLayeredPane2.add(jTextField6);
        jTextField6.setBounds(350, 180, 100, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 100, 153));
        jButton1.setText("Login in instead");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton1);
        jButton1.setBounds(100, 423, 150, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 100, 153));
        jButton2.setText("Create  Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton2);
        jButton2.setBounds(290, 423, 150, 40);
        jLayeredPane2.add(jPasswordField1);
        jPasswordField1.setBounds(130, 280, 100, 30);

        jLabel7.setText("CONFIRM PASSWORD");
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(240, 290, 107, 14);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 100, 153));
        jLabel9.setText(" SIGN UP HERE");
        jLabel9.setOpaque(true);
        jLayeredPane2.add(jLabel9);
        jLabel9.setBounds(180, 80, 180, 20);
        jLayeredPane2.add(jPasswordField2);
        jPasswordField2.setBounds(360, 280, 120, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_Signup.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel8);
        jLabel8.setBounds(0, 0, 540, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String firstname =jTextField1.getText();
        String lastname =jTextField2.getText();
        String username =jTextField3.getText();
        String password =jPasswordField1.getText();
        String conpassword =jPasswordField2.getText();
        String email =jTextField5.getText();
        String phoneno =jTextField6.getText();
        
                
        if (firstname.isEmpty())
        JOptionPane.showMessageDialog(this,"Name not Entered");
        else if (lastname.isEmpty())
        JOptionPane.showMessageDialog(this,"lastname not entered");
        else if (username.isEmpty())
        JOptionPane.showMessageDialog(this,"username not entered");
        else if (password.isEmpty())
        JOptionPane.showMessageDialog(this,"password not entered");
        else if (!(password.equals(conpassword)))
        JOptionPane.showMessageDialog(this,"password doesnnot match");
        else if (email.isEmpty())
        JOptionPane.showMessageDialog(this,"email not entered");
        else if (phoneno.isEmpty())
        JOptionPane.showMessageDialog(this,"phoneno not entered");
        
            
        
        else

        try
        {   Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "Insert INTO Customers ( `customer_username`, `customer_password`, `customer_firstname`,`customer_lastname`, `customer_phone`, `customer_email`) values('"+username+"','"+password+"','"+firstname+"','"+lastname+"','"+email+"','"+phoneno+",');" ;
            stmt.executeUpdate(query);           
            con.close();
            stmt.close(); 
            this.dispose();
            new ADDRESS_CUSTOMER(username).setVisible(true);
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new LOGIN_CUSTOMER().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP_CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP_CUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel jLogo1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
