/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class UPDATEINFO_CUSTOMERS extends javax.swing.JFrame {
Integer identity;
    /**
     * Creates new form UPDATEINFO_CUSTOMERS
     */
    public UPDATEINFO_CUSTOMERS() {
        initComponents();
    }
    
    public UPDATEINFO_CUSTOMERS(Integer id) {
        identity = id;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLogo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane2.add(jTextField1);
        jTextField1.setBounds(240, 190, 100, 30);

        jLabel2.setText("FIRST NAME");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(170, 200, 70, 14);

        jLabel3.setText("LAST NAME");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(170, 240, 70, 14);

        jLabel4.setText("PHONE NO");
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(170, 290, 70, 14);

        jLabel5.setText("EMAIL");
        jLayeredPane2.add(jLabel5);
        jLabel5.setBounds(180, 330, 30, 14);
        jLayeredPane2.add(jTextField2);
        jTextField2.setBounds(240, 230, 100, 30);
        jLayeredPane2.add(jTextField5);
        jTextField5.setBounds(240, 280, 100, 30);
        jLayeredPane2.add(jTextField6);
        jTextField6.setBounds(240, 320, 100, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 100, 153));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton1);
        jButton1.setBounds(300, 440, 180, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 100, 153));
        jButton2.setText("UPDATE INFORMATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton2);
        jButton2.setBounds(60, 440, 200, 40);

        jLogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_logo(Low).png"))); // NOI18N
        jLayeredPane2.add(jLogo1);
        jLogo1.setBounds(60, 40, 102, 52);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 100, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UPDATE HERE");
        jLabel7.setOpaque(true);
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(160, 90, 190, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ddd/DDD_Signup.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(0, -10, 540, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new DASHBOARD_CUSTOMER(identity).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String firstname =jTextField1.getText();
        String lastname =jTextField2.getText();
        String email =jTextField5.getText();
        String phoneno =jTextField6.getText();

        if (firstname.isEmpty())
        JOptionPane.showMessageDialog(this,"Name not Entered");
        else if (lastname.isEmpty())
        JOptionPane.showMessageDialog(this,"lastname not entered");
        else if (email.isEmpty())
        JOptionPane.showMessageDialog(this,"email not entered");
        else if (phoneno.isEmpty())
        JOptionPane.showMessageDialog(this,"phoneno not entered");

        else

        try
        {   Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "Update Customers set customer_firstname = '"+firstname+"', customer_lastname = '"+lastname+"', customer_phone = '"+phoneno+"', customer_email = '"+email+"' where customer_id = '"+ identity +"';";
            int del = JOptionPane.showConfirmDialog(rootPane,"Do you really want to Update?" );
                if (del == 0)
                {
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(rootPane,"Record Updated" );
                    
                    
                }
            con.close();
            stmt.close();
            
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {   Class.forName("java.sql.DriverManager");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/DDD","root", "");
            Statement stmt1 = (Statement) con1.createStatement();
            String a = "Select `customer_firstname`,`customer_lastname`, `customer_phone`, `customer_email` from  Customers where customer_id = "+ identity+";";
            ResultSet rs=stmt1.executeQuery(a);
            
            while (rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField5.setText(rs.getString(3));
                jTextField6.setText(rs.getString(4));
            }
            
            
            con1.close();
            stmt1.close();
            
        }
        catch(Exception e)
        {            JOptionPane.showMessageDialog(this,e.getMessage());        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATEINFO_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATEINFO_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATEINFO_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATEINFO_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEINFO_CUSTOMERS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel jLogo1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
